### ISSUE TITLE
Ствараць інсталятар дойкі праз GitHub actions/workflows

### ISSUE THREAD

**Issue by alies-dev** [diglabby/doika#796]
На дадзены момант мы гэта рабім праз Трэвіс, які па-ціху зашінаецца і вельмі павольны

Start from:

```yml
name: Build installer

on:
  release:
    types: [published]

jobs:
  - uses: actions/checkout@v2

  - name: Create and upload artifacts
  - uses: ncipollo/release-action@v1
    if: startsWith(github.ref, 'refs/tags/')
    with:
      artifacts: "release.tar.gz,foo/*.txt"
      bodyFile: "body.md"
      token: ${{ secrets.GITHUB_TOKEN }}
```

Код для трэвіса:
https://github.com/diglabby/doika/blob/4ea23f0d99f33c913b8aed07cd3caa6baa620754/.travis.yml#L50-L67
